name: deploy
on:
  push:
    branches:
      - main
    paths:
      - "handler.py"
      - "Pipfile*"
  pull_request:
    branches:
      - main
    paths:
      - "handler.py"
      - "Pipfile*"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          architecture: "x64"
          cache: "pipenv"
          cache-dependency-path: Pipfile.lock
      - name: Install pipenv
        run: |
          pip install --prefer-binary -r requirements.txt
          pipenv install --dev
      - name: Check linting & formatting
        run: |
          pipenv run flake8 .
          pipenv run black --check .
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          architecture: "x64"
          cache: "pipenv"
          cache-dependency-path: Pipfile.lock
      - name: Install pipenv
        run: |
          pip install --prefer-binary -r requirements.txt
          pipenv install
      - name: Create deployment package
        run: |
          pipenv requirements > requirements.txt
          pip install --prefer-binary -r requirements.txt --target ${{ github.workspace }}/package
          cp handler.py ${{ github.workspace }}/package
      - name: Upload package
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lambda-package
          path: ${{ github.workspace}}/package
          overwrite: true
          retention-days: 1
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [package, check]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download package
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ${{ github.workspace }}/package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@d496277188b89f0be02d7a2216fc912c0427702a # v1.1.2
        with:
          function-name: ${{ vars.LAMBDA_NAME }}
          package-type: Zip
          runtime: python3.14
          handler: handler.handler
          publish: false
          code-artifacts-dir: ${{ github.workspace }}/package
